### ISSUE TITLE
Container shouldn't run as Root

### ISSUE THREAD

**Issue by MarkDeckert** [kubernetes-sigs/dashboard-metrics-scraper#16]
### Issue:
The metrics sidecar doesn't have a need to be running as root.  In keeping with the least privilege security principle it should be run as a higher UID.  However, when trying to run the container as a different user, it fails during startup when trying to write a log to /tmp.

### Problem:
The /tmp directory is copied in during the build process and this is owned by root.  Therefore the entire container needs to be executed as root just to function.  This lowers the effectiveness of strict PodSecurityPolicy and overall cluster security posture.

### Suggested resolution:
(Note: My initial suggested resolution doesn't actually work since it's a scratch image.  I've edited this out and will update later or submit PR when I get a chance.)

**Comment by jeefy** [comment]
I'll tackle this this weekend unless you beat me to it. :)

/assign

**Comment by MarkDeckert** [comment]
No problemo! - I took a shot at it and added a --chown arg to two COPY lines and a USER line.  Tested the new image in my cluster and it works now as a non-root user.  Just chose 1501 arbitrarily, but obviously any number would do.

To pass a restrictive PodSecurityPolicy the deployment yaml would still need to specify the runAsUser in the securityContext, but that's a different repo.

**Comment by jchauncey** [comment]
Noticed that this issue was still open. We are seeing this issue pop up on security scans and would like to get it fixed. Because the final container is a scratch image you need to create a user in the builder image and copy it over to it exists when the container starts. Is this something you would accept a pr on?

**Comment by jeefy** [comment]
Absolutely!

**Comment by jchauncey** [comment]
K ill send a pr over shortly. I havent used this image before so Im trying to figure out how to test it =)

**Comment by jeefy** [comment]
Fixed by #32 

/close
