### ISSUE TITLE
Does not scrape any node or pods

### ISSUE THREAD

**Issue by Vrtak-CZ** [kubernetes-sigs/dashboard-metrics-scraper#17]
Hi,

i'm just deployed Kubernetes Dashboard `2.0.0-beta1` with this scraper `1.0.0` and in logs i see `Database updated: 0 nodes, 0 pods` but there are 3 nodes and lots of pods. And yes `metrics-server` is deployed in cluster. It's AWS EKS `1.13.7` cluster. Maybe i'm just doing something wrong.

For deployment i used this template: https://github.com/kubernetes/dashboard/blob/v2.0.0-beta1/aio/deploy/recommended.yaml

**Comment by jeefy** [comment]
Two things that come to mind.

* Some RBAC config preventing scraper from hitting the metrics API
* Metrics Server isn't capturing anything (I personally doubt this, it's pretty solid)

Is there anything else in the scraper or metrics-server logs? Also, could you possibly do something like `kubectl proxy` and try to hit the metrics.k8s.io endpoint yourself? If you need any guidance with that, just ping me. :)

Thanks!

**Comment by Vrtak-CZ** [comment]
Thank you. So i made some research and debugging and problem is with metrics server resp. wit whole cluster because DNS in cluster is not able resolve `*.*.compute.internal` domains. So my problem is not related to metrics-scraper. One more time thank you.
