### ISSUE TITLE
Cut v1.0.2 release

### ISSUE THREAD

**Issue by jeefy** [kubernetes-sigs/dashboard-metrics-scraper#20]
- [x] Cut a v1.0.2 release on Docker Hub 
- [x] Update Dashboard Manifests

/assign @maciaszczykm @floreks 
/priority important-soon

**Comment by zimme** [comment]
Any idea if this is days, weeks or months away?

**Comment by Ognian** [comment]
Need this https://github.com/kubernetes-sigs/dashboard-metrics-scraper/pull/19
any chance to get it sooner than soon...

**Comment by floreks** [comment]
We'll try to update scraper tomorrow.

**Comment by zimme** [comment]
This can be closed 👍
