### ISSUE TITLE
dashboard-metrics-scraper Pod Goes into CrashLoopBackOff

### ISSUE THREAD

**Issue by krishvoor** [kubernetes-sigs/dashboard-metrics-scraper#22]
Environment

I am trying to setup Kubernetes Dashboard using the instructions listed here https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/ on

Kubernetes v1.16.0 with
GitCommit:2bd9643cee5b3b3a5ecbd3af49d09018f0773c77
GitTreeState:clean& BuildDate:"2019-09-18T14:36:53Z" &
GoVersion:"go1.12.9" with Compiler:"gc"on Platform:"linux/ppc64le"

Installation method: apt sources
Kubernetes version:
Dashboard version:
Operating system: Ubuntu 1804 ppc64le
Node.js version ('node --version' output): NA
Go version ('go version' output): NA

Steps to reproduce

    After bootstrapping the Kubernetes Cluster ( single node cluster ), I used Flannel as backboone for communication via
    kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

2)Applied the Kubernetes Dashboard related changes via per the commands listed here
https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/#deploying-the-dashboard-ui
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta4/aio/deploy/recommended.yaml
Observed result

root@ubuntu:/home/harsha/dashboard# kubectl logs dashboard-metrics-scraper-566cddb686-2sbq9 -n kubernetes-dashboard
{"level":"info","msg":"Kubernetes host: https://10.96.0.1:443","time":"2019-09-30T10:56:33Z"}
{"level":"fatal","msg":"Unable to initialize database tables: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub","time":"2019-09-30T10:56:33Z"}
root@ubuntu:/home/harsha/dashboard# 

Expected result

Deployment should happen seamlessly.

**Comment by krishvoor** [comment]
@mkumatag ^^^
@floreks - Here you go.

**Comment by floreks** [comment]
Metrics scraper does not support `ppc64le` architecture properly right now. You are welcome to extend our [build script](https://github.com/kubernetes-sigs/dashboard-metrics-scraper/blob/master/hack/build.sh) to support it as you are able to test your changes. I wouldn't be able to test it on such architecture.

Another thing is that K8S Dashboard does not support K8S `v1.16`. `beta5` will add support for that.

**Comment by floreks** [comment]
Closing as it is not a bug. We do not support the mentioned architecture.

/close
