### ISSUE TITLE
Do you consider to support arch mips?

### ISSUE THREAD

**Issue by ZzzJing** [kubernetes-sigs/dashboard-metrics-scraper#26]
I could provide code for images build in arch mips.

**Comment by maciaszczykm** [comment]
@ZzzJing sorry for really late answer, if you are still willing to contribute then we would welcome such PR.

**Comment by ZzzJing** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by maciaszczykm** [comment]
Closing as stale.
