### ISSUE TITLE
request v1.0.5 release

### ISSUE THREAD

**Issue by edmondsw** [kubernetes-sigs/dashboard-metrics-scraper#30]
v1.0.4 has a runtime error on ppc64le that appears to be fixed by https://github.com/kubernetes-sigs/dashboard-metrics-scraper/commit/33ef516a2779fc9410cd29f643796458d74728bc . What is the outlook for a v1.0.5 release that would pick up that fix? Thanks!

**Comment by jeefy** [comment]
v1.0.5 has been released :)

/close
