### ISSUE TITLE
Dashboard pods and replicas keep spinning

### ISSUE THREAD

**Issue by krishnakc1** [kubernetes-sigs/dashboard-metrics-scraper#48]
Hello,
We notice that the dashboard spins on the display of pods and deployments sometimes on few namespaces. Other kubernetes objects like services etc., in those namespaces are displayed well. The deployments in Kubernetes cluster itself are running good.
Sometimes a restart of the kubernetes dashboard metrics pod helps but after few days it reappears
Kubernetes version - 1.14.3
Kubernetes dashboard version - v2.0.0 
Kubernetes dashboard metrics - v1.0.4

I can upgrade to the later versions and check, Is there some one who has seen the issue?
![image](https://user-images.githubusercontent.com/26587125/169037904-beb5635f-7c32-4480-993e-1b945089130f.png)

**Comment by maciaszczykm** [comment]
Hi, can you provide logs from containers and check if there is anything in the browser as well?

**Comment by floreks** [comment]
Unsupported dashboard/scraper versions used. Also, this does not seem to be related to scraper directly.

/close
