### ISSUE TITLE
S390x (and other architectures) are not supported for latest version of metrics scraper

### ISSUE THREAD

**Issue by Joseph-Goergen** [kubernetes-sigs/dashboard-metrics-scraper#54]
The metrics scraper v1.0.8 does not support s390x. v1.0.7 does appear to support it

![image](https://user-images.githubusercontent.com/49251717/211390587-a29ed933-9958-4c03-b0d9-284b41e1c814.png)

If you run a `skopeo inspect` on the image, it says it supports the other architectures

```
# skopeo --override-arch=s390x inspect docker://docker.io/kubernetesui/metrics-scraper:v1.0.8 --raw
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 736,
         "digest": "sha256:43227e8286fd379ee0415a5e2156a9439c4056807e3caa38e1dd413b0644807a",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
...
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 736,
         "digest": "sha256:a8a4f13158fef2725272152321c122dc85ebcb3a6a62a97623c5fd4251b5dd62",
         "platform": {
            "architecture": "s390x",
            "os": "linux"
         }
      }
   ]
}%
```

But `docker inspect` says otherwise

```
# docker pull --platform s390x docker.io/kubernetesui/metrics-scraper:v1.0.8
v1.0.8: Pulling from kubernetesui/metrics-scraper
72d99d15fd85: Pull complete
6be5fb9ff547: Pull complete
Digest: sha256:76049887f07a0476dc93efc2d3569b9529bf982b22d29f356092ce206e98765c
Status: Downloaded newer image for kubernetesui/metrics-scraper:v1.0.8
docker.io/kubernetesui/metrics-scraper:v1.0.8
# docker inspect docker.io/kubernetesui/metrics-scraper:v1.0.8 | jq -r '.[].Architecture'
amd64
```

We are asking for a new patch release that re-supports the other architectures.

**Comment by afbjorklund** [comment]
I think the `docker build` command is missing a `--platform`, so the image gets the wrong info...
The actual contents seem OK though, being cross-compiled using the `GOARCH` cross-compilation.

https://github.com/kubernetes-sigs/dashboard-metrics-scraper/blob/master/hack/deploy.sh

**Comment by afbjorklund** [comment]
Main difference between the images seem to be the use of BuildKit ? (Says `docker history` anyway)

**Comment by tumberino** [comment]
@afbjorklund Is it possible to get a new release of the docker images to have the correct architecture labels? Since #56 has been merged.

**Comment by tumberino** [comment]
@maciaszczykm Is there a plan for a new release or can the get new images published with the architecture fix in?

**Comment by maciaszczykm** [comment]
New images are there, but it will take few more weeks to release them with chart etc.

**Comment by rtheis** [comment]
@maciaszczykm where do we find the images? https://hub.docker.com/r/kubernetesui/metrics-scraper/tags show v1.0.8 as the latest release.

**Comment by maciaszczykm** [comment]
New scraper image was just released.
